copy StringResources.en.resx StringResources.cs.resx
copy StringResources.en.resx StringResources.da.resx
copy StringResources.en.resx StringResources.de.resx
copy StringResources.en.resx StringResources.es.resx
copy StringResources.en.resx StringResources.fi.resx
copy StringResources.en.resx StringResources.he.resx
copy StringResources.en.resx StringResources.it.resx
copy StringResources.en.resx StringResources.ja.resx
copy StringResources.en.resx StringResources.nl.resx
copy StringResources.en.resx StringResources.no.resx
copy StringResources.en.resx StringResources.pl.resx
copy StringResources.en.resx StringResources.pt.resx
copy StringResources.en.resx StringResources.ru.resx
copy StringResources.en.resx StringResources.sk.resx
copy StringResources.en.resx StringResources.sv.resx
copy StringResources.en.resx StringResources.zh-CN.resx