//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarminFitnessPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GarminFitnessPlugin.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to logbook.
        /// </summary>
        internal static string AddDailyViewCheckBoxText {
            get {
                return ResourceManager.GetString("AddDailyViewCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string AndText {
            get {
                return ResourceManager.GetString("AndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow workouts with more than 20 steps.
        /// </summary>
        internal static string AutoSplitCheckBoxText {
            get {
                return ResourceManager.GetString("AutoSplitCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string AutoText {
            get {
                return ResourceManager.GetString("AutoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the data in the profile is biking specific.  This data includes the different power zones as well as the bike profiles.  If you don&apos;t have a biking compatible unit you can skip this section..
        /// </summary>
        internal static string BikeProfileExplanationText {
            get {
                return ResourceManager.GetString("BikeProfileExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike {0} ({1}).
        /// </summary>
        internal static string BikeProfileMenuItemText {
            get {
                return ResourceManager.GetString("BikeProfileMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biking.
        /// </summary>
        internal static string BikingText {
            get {
                return ResourceManager.GetString("BikingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date :.
        /// </summary>
        internal static string BirthDateLabelText {
            get {
                return ResourceManager.GetString("BirthDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string BrowseButtonText {
            get {
                return ResourceManager.GetString("BrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my cadence between {0} and {1} {2}..
        /// </summary>
        internal static string CadenceRangeTargetDescriptionText {
            get {
                return ResourceManager.GetString("CadenceRangeTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadence Settings.
        /// </summary>
        internal static string CadenceSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("CadenceSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my cadence in a certain zone.
        /// </summary>
        internal static string CadenceTargetComboBoxText {
            get {
                return ResourceManager.GetString("CadenceTargetComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this cadence zone for my workouts :.
        /// </summary>
        internal static string CadenceZoneSelectionLabelText {
            get {
                return ResourceManager.GetString("CadenceZoneSelectionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my cadence in zone {0}..
        /// </summary>
        internal static string CadenceZoneTargetDescriptionText {
            get {
                return ResourceManager.GetString("CadenceZoneTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After I have burned a certain number of calories.
        /// </summary>
        internal static string CaloriesDurationComboBoxText {
            get {
                return ResourceManager.GetString("CaloriesDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go until I burn {0} calories..
        /// </summary>
        internal static string CaloriesDurationDescriptionText {
            get {
                return ResourceManager.GetString("CaloriesDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many calories?.
        /// </summary>
        internal static string CaloriesDurationLabelText {
            get {
                return ResourceManager.GetString("CaloriesDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesText {
            get {
                return ResourceManager.GetString("CategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For your workouts to be correctly categorized on your unit you must associate every SportTracks activity category with it&apos;s corresponding Garmin activity category.  Doing so allows your workouts to use the right heart rate zones and speed zones as setup in your profile..
        /// </summary>
        internal static string CategoryAssociationExplanationText {
            get {
                return ResourceManager.GetString("CategoryAssociationExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin category association.
        /// </summary>
        internal static string CategoryAssociationText {
            get {
                return ResourceManager.GetString("CategoryAssociationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the setup wizard successfully.  The plugin is now available from the &quot;Select view&quot; menu.  Note that all the settings are always available in the Garmin Fitness Plugin &quot;Settings&quot; page and in the &quot;Profile&quot; view..
        /// </summary>
        internal static string CompletedExplanationText {
            get {
                return ResourceManager.GetString("CompletedExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close the wizard click on &quot;Finish&quot;.
        /// </summary>
        internal static string CompletedLabelText {
            get {
                return ResourceManager.GetString("CompletedLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string CompletedText {
            get {
                return ResourceManager.GetString("CompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up the plugin, click on &quot;Next&quot;.
        /// </summary>
        internal static string ContinueLabelText {
            get {
                return ResourceManager.GetString("ContinueLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open this data with this version of the Garmin Fitness Plugin, please update to the latest version..
        /// </summary>
        internal static string DataTooRecentErrorText {
            get {
                return ResourceManager.GetString("DataTooRecentErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Export Directory.
        /// </summary>
        internal static string DefaultExportDirectoryGroupBoxText {
            get {
                return ResourceManager.GetString("DefaultExportDirectoryGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the heart rate zones from :.
        /// </summary>
        internal static string DefaultHeartRateZoneLabelText {
            get {
                return ResourceManager.GetString("DefaultHeartRateZoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the power zones from :.
        /// </summary>
        internal static string DefaultPowerZoneLabelText {
            get {
                return ResourceManager.GetString("DefaultPowerZoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the speed zones from :.
        /// </summary>
        internal static string DefaultSpeedZoneLabelText {
            get {
                return ResourceManager.GetString("DefaultSpeedZoneLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsText {
            get {
                return ResourceManager.GetString("DetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the Garmin Cummunicator Plugin.  Please make sure you have SportTracks version 2.0.3170 or later and Garmin Cummunicator Plugin installed and activated in Internet Explorer..
        /// </summary>
        internal static string DeviceCommunicationErrorText {
            get {
                return ResourceManager.GetString("DeviceCommunicationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After I go a certain distance.
        /// </summary>
        internal static string DistanceDurationComboBoxText {
            get {
                return ResourceManager.GetString("DistanceDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go {0:0.00} {1}..
        /// </summary>
        internal static string DistanceDurationDescriptionText {
            get {
                return ResourceManager.GetString("DistanceDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How far?.
        /// </summary>
        internal static string DistanceDurationLabelText {
            get {
                return ResourceManager.GetString("DistanceDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a decimal number between {0:0.00} and {1:0.00}.
        /// </summary>
        internal static string DoubleRangeValidationText {
            get {
                return ResourceManager.GetString("DoubleRangeValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biking profile.
        /// </summary>
        internal static string EditBikingProfileText {
            get {
                return ResourceManager.GetString("EditBikingProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can edit your personal information that will be stored in your profile.  Take note that the display of your workouts is affected by the way you choose to edit your zones (BPM vs. % max HR and speed vs. pace) and that these zones are different for every sport..
        /// </summary>
        internal static string EditProfileExplanationText {
            get {
                return ResourceManager.GetString("EditProfileExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditProfileText {
            get {
                return ResourceManager.GetString("EditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit my profile manually.
        /// </summary>
        internal static string EditRadioButtonText {
            get {
                return ResourceManager.GetString("EditRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        internal static string ExportAllText {
            get {
                return ResourceManager.GetString("ExportAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while exporting the profile..
        /// </summary>
        internal static string ExportProfileFailedText {
            get {
                return ResourceManager.GetString("ExportProfileFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile has been successfully exported to the device..
        /// </summary>
        internal static string ExportProfileSuccessText {
            get {
                return ResourceManager.GetString("ExportProfileSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Selected.
        /// </summary>
        internal static string ExportSelectedText {
            get {
                return ResourceManager.GetString("ExportSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportText {
            get {
                return ResourceManager.GetString("ExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while exporting workouts..
        /// </summary>
        internal static string ExportWorkoutsFailedText {
            get {
                return ResourceManager.GetString("ExportWorkoutsFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts have been successfully exported..
        /// </summary>
        internal static string ExportWorkoutsSuccessText {
            get {
                return ResourceManager.GetString("ExportWorkoutsSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleText {
            get {
                return ResourceManager.GetString("FemaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Files.
        /// </summary>
        internal static string FileDescriptionText {
            get {
                return ResourceManager.GetString("FileDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up the plugin later, click on &quot;Finish&quot;.
        /// </summary>
        internal static string FinishLabelText {
            get {
                return ResourceManager.GetString("FinishLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force split.
        /// </summary>
        internal static string ForceSplitCheckBoxText {
            get {
                return ResourceManager.GetString("ForceSplitCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Device.
        /// </summary>
        internal static string FromDeviceText {
            get {
                return ResourceManager.GetString("FromDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File.
        /// </summary>
        internal static string FromFileText {
            get {
                return ResourceManager.GetString("FromFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Threshold Power :.
        /// </summary>
        internal static string FTPLabelText {
            get {
                return ResourceManager.GetString("FTPLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Fitness.
        /// </summary>
        internal static string GarminFitnessText {
            get {
                return ResourceManager.GetString("GarminFitnessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to use the Garmin mode.
        /// </summary>
        internal static string GarminModeRadioButtonText {
            get {
                return ResourceManager.GetString("GarminModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin or SportTracks mode.
        /// </summary>
        internal static string GarminOrSTText {
            get {
                return ResourceManager.GetString("GarminOrSTText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin.
        /// </summary>
        internal static string GarminText {
            get {
                return ResourceManager.GetString("GarminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear Weight :.
        /// </summary>
        internal static string GearWeightLabelText {
            get {
                return ResourceManager.GetString("GearWeightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender :.
        /// </summary>
        internal static string GenderLabelText {
            get {
                return ResourceManager.GetString("GenderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Speed.
        /// </summary>
        internal static string GTCSpeedZone10Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone10Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb 4.
        /// </summary>
        internal static string GTCSpeedZone1Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb 3.
        /// </summary>
        internal static string GTCSpeedZone2Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb 2.
        /// </summary>
        internal static string GTCSpeedZone3Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb 1.
        /// </summary>
        internal static string GTCSpeedZone4Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat 3.
        /// </summary>
        internal static string GTCSpeedZone5Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat 2.
        /// </summary>
        internal static string GTCSpeedZone6Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat 1.
        /// </summary>
        internal static string GTCSpeedZone7Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent.
        /// </summary>
        internal static string GTCSpeedZone8Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        internal static string GTCSpeedZone9Text {
            get {
                return ResourceManager.GetString("GTCSpeedZone9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has cadence sensor.
        /// </summary>
        internal static string HasCadenceText {
            get {
                return ResourceManager.GetString("HasCadenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has power sensor.
        /// </summary>
        internal static string HasPowerText {
            get {
                return ResourceManager.GetString("HasPowerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When my heart rate gets above a certain level.
        /// </summary>
        internal static string HeartRateAboveDurationComboBoxText {
            get {
                return ResourceManager.GetString("HeartRateAboveDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go until me heart rate gets above {0} {1}..
        /// </summary>
        internal static string HeartRateAboveDurationDescriptionText {
            get {
                return ResourceManager.GetString("HeartRateAboveDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When my heart rate gets below a certain level.
        /// </summary>
        internal static string HeartRateBelowDurationComboBoxText {
            get {
                return ResourceManager.GetString("HeartRateBelowDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go until me heart rate gets below {0} {1}..
        /// </summary>
        internal static string HeartRateBelowDurationDescriptionText {
            get {
                return ResourceManager.GetString("HeartRateBelowDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What heart rate level?.
        /// </summary>
        internal static string HeartRateDurationLabelText {
            get {
                return ResourceManager.GetString("HeartRateDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my heart rate between {0} and {1} {2}..
        /// </summary>
        internal static string HeartRateRangeTargetDescriptionText {
            get {
                return ResourceManager.GetString("HeartRateRangeTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my heart rate in a certain zone.
        /// </summary>
        internal static string HeartRateTargetComboBoxText {
            get {
                return ResourceManager.GetString("HeartRateTargetComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my heart rate in zone {0}..
        /// </summary>
        internal static string HeartRateZoneTargetDescriptionText {
            get {
                return ResourceManager.GetString("HeartRateZoneTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High :.
        /// </summary>
        internal static string HighLabelText {
            get {
                return ResourceManager.GetString("HighLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string HighText {
            get {
                return ResourceManager.GetString("HighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate Settings.
        /// </summary>
        internal static string HRSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("HRSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate Zones.
        /// </summary>
        internal static string HRZonesGroupBoxText {
            get {
                return ResourceManager.GetString("HRZonesGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order for your workouts to use the right zones, we must setup these zones.  Even if you setup the plugin in SportTracks mode, your profile in used for the display (speed vs. pace, BPM vs. % max HR) so it is important to setup your profile.  You can either import you profile from your unit or you can edit it manually..
        /// </summary>
        internal static string ImportEditExplanationText {
            get {
                return ResourceManager.GetString("ImportEditExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importing profiles.
        /// </summary>
        internal static string ImportingProfilesText {
            get {
                return ResourceManager.GetString("ImportingProfilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to importing workouts.
        /// </summary>
        internal static string ImportingWorkoutsText {
            get {
                return ResourceManager.GetString("ImportingWorkoutsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import or edit profile.
        /// </summary>
        internal static string ImportOrEditProfileText {
            get {
                return ResourceManager.GetString("ImportOrEditProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while importing the profile..
        /// </summary>
        internal static string ImportProfileErrorText {
            get {
                return ResourceManager.GetString("ImportProfileErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import my profile from my unit.
        /// </summary>
        internal static string ImportRadioButtonText {
            get {
                return ResourceManager.GetString("ImportRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while importing the workouts..
        /// </summary>
        internal static string ImportWorkoutsErrorText {
            get {
                return ResourceManager.GetString("ImportWorkoutsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to configure the zones independently.
        /// </summary>
        internal static string IndependentModeRadioButtonText {
            get {
                return ResourceManager.GetString("IndependentModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be an integer between {0} and {1}.
        /// </summary>
        internal static string IntegerRangeValidationText {
            get {
                return ResourceManager.GetString("IntegerRangeValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered workout name is invalid.  The name must be unique and cannot be empty..
        /// </summary>
        internal static string InvalidWorkoutNameText {
            get {
                return ResourceManager.GetString("InvalidWorkoutNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I press the &apos;Lap&apos; button on my device.
        /// </summary>
        internal static string LapButtonDurationComboBoxText {
            get {
                return ResourceManager.GetString("LapButtonDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go until I press the &apos;lap&apos; button on my device..
        /// </summary>
        internal static string LapButtonDurationDescriptionText {
            get {
                return ResourceManager.GetString("LapButtonDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last export date :.
        /// </summary>
        internal static string LastExportDateText {
            get {
                return ResourceManager.GetString("LastExportDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low :.
        /// </summary>
        internal static string LowLabelText {
            get {
                return ResourceManager.GetString("LowLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LowText {
            get {
                return ResourceManager.GetString("LowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleText {
            get {
                return ResourceManager.GetString("MaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to configure your zone usage manually.  Please select the mode to use for each type of zone available in the plugin..
        /// </summary>
        internal static string ManualSTGarminZonesExplanationText {
            get {
                return ResourceManager.GetString("ManualSTGarminZonesExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Heart Rate :.
        /// </summary>
        internal static string MaxHRLabelText {
            get {
                return ResourceManager.GetString("MaxHRLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string MillimeterText {
            get {
                return ResourceManager.GetString("MillimeterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteAbbrText {
            get {
                return ResourceManager.GetString("MinuteAbbrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the things that the Garmin Fitness Plugin allows is a better integration with SportTracks.  What this means is that it is possible to use the SportTracks defined heart rate, speed and power zones instead of the ones defined by Garmin.  This choice can also be customized per zone type..
        /// </summary>
        internal static string ModeExplanationText {
            get {
                return ResourceManager.GetString("ModeExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        internal static string NameLabelText {
            get {
                return ResourceManager.GetString("NameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To create an activity from this workout, you need at least 1 activity already in your logbook.  It seems your logbook is empty so please create an empty activity, reschedule your workout then delete that temporary activity..
        /// </summary>
        internal static string NeedActivityTemplateText {
            get {
                return ResourceManager.GetString("NeedActivityTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never exported.
        /// </summary>
        internal static string NeverExportedText {
            get {
                return ResourceManager.GetString("NeverExportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name :.
        /// </summary>
        internal static string NewNameLabelText {
            get {
                return ResourceManager.GetString("NewNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device {0} does not support {1}..
        /// </summary>
        internal static string NoDeviceSupportText {
            get {
                return ResourceManager.GetString("NoDeviceSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes :.
        /// </summary>
        internal static string NotesLabelText {
            get {
                return ResourceManager.GetString("NotesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t have a specific target for this step.
        /// </summary>
        internal static string NullTargetComboBoxText {
            get {
                return ResourceManager.GetString("NullTargetComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NullTargetDescriptionText {
            get {
                return ResourceManager.GetString("NullTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NumberText {
            get {
                return ResourceManager.GetString("NumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer :.
        /// </summary>
        internal static string OdometerLabelText {
            get {
                return ResourceManager.GetString("OdometerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Workout.
        /// </summary>
        internal static string OpenFileText {
            get {
                return ResourceManager.GetString("OpenFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherText {
            get {
                return ResourceManager.GetString("OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my pace between {0:00}:{1:00} and {2:00}:{3:00} min/{4}..
        /// </summary>
        internal static string PaceRangeTargetDescriptionText {
            get {
                return ResourceManager.GetString("PaceRangeTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to part {0}/{1}.
        /// </summary>
        internal static string PartNumberingNotesText {
            get {
                return ResourceManager.GetString("PartNumberingNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to paste the steps, your workout cannot contain that many steps.  The maximum number of steps in a workout is 20..
        /// </summary>
        internal static string PasteStepErrorText {
            get {
                return ResourceManager.GetString("PasteStepErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /h.
        /// </summary>
        internal static string PerHourText {
            get {
                return ResourceManager.GetString("PerHourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my power between {0} and {1} watts..
        /// </summary>
        internal static string PowerRangeTargetDescriptionText {
            get {
                return ResourceManager.GetString("PowerRangeTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Settings.
        /// </summary>
        internal static string PowerSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("PowerSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my power in a certain zone.
        /// </summary>
        internal static string PowerTargetComboBoxText {
            get {
                return ResourceManager.GetString("PowerTargetComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this power zone for my workouts :.
        /// </summary>
        internal static string PowerZoneSelectionLabelText {
            get {
                return ResourceManager.GetString("PowerZoneSelectionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Zones.
        /// </summary>
        internal static string PowerZonesGroupBoxText {
            get {
                return ResourceManager.GetString("PowerZonesGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my power in zone {0}..
        /// </summary>
        internal static string PowerZoneTargetDescriptionText {
            get {
                return ResourceManager.GetString("PowerZoneTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileText {
            get {
                return ResourceManager.GetString("ProfileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh devices.
        /// </summary>
        internal static string RefreshButtonText {
            get {
                return ResourceManager.GetString("RefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this option will use the following name for the workout..
        /// </summary>
        internal static string RenameExplanationLabelText {
            get {
                return ResourceManager.GetString("RenameExplanationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameLabelText {
            get {
                return ResourceManager.GetString("RenameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat the steps below {0} times:.
        /// </summary>
        internal static string RepeatStepDescriptionText {
            get {
                return ResourceManager.GetString("RepeatStepDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many repetitions do you want to do?.
        /// </summary>
        internal static string RepetitionCountLabelText {
            get {
                return ResourceManager.GetString("RepetitionCountLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition Properties.
        /// </summary>
        internal static string RepetitionPropertiesGroupText {
            get {
                return ResourceManager.GetString("RepetitionPropertiesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting this option will overwrite the current workout that has the same name..
        /// </summary>
        internal static string ReplaceExplanationLabelText {
            get {
                return ResourceManager.GetString("ReplaceExplanationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string ReplaceLabelText {
            get {
                return ResourceManager.GetString("ReplaceLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace or rename?.
        /// </summary>
        internal static string ReplaceRenameDialogText {
            get {
                return ResourceManager.GetString("ReplaceRenameDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a workout present that has the same name.  You can either replace the current workout or rename the new one..
        /// </summary>
        internal static string ReplaceRenameIntroLabelText {
            get {
                return ResourceManager.GetString("ReplaceRenameIntroLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting step.
        /// </summary>
        internal static string RestingCheckBoxText {
            get {
                return ResourceManager.GetString("RestingCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resting heart rate :.
        /// </summary>
        internal static string RestingHeartRateLabelText {
            get {
                return ResourceManager.GetString("RestingHeartRateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string RestText {
            get {
                return ResourceManager.GetString("RestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string RunningText {
            get {
                return ResourceManager.GetString("RunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run setup wizard....
        /// </summary>
        internal static string RunWizardText {
            get {
                return ResourceManager.GetString("RunWizardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string ScheduleBannerText {
            get {
                return ResourceManager.GetString("ScheduleBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category for workout .
        /// </summary>
        internal static string SelectCategoryDialogText {
            get {
                return ResourceManager.GetString("SelectCategoryDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a date.
        /// </summary>
        internal static string SelectDateText {
            get {
                return ResourceManager.GetString("SelectDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your device below.  If your device doesn&apos;t appear, make sure it is connected to your PC and hit the refresh button..
        /// </summary>
        internal static string SelectDeviceIntroText {
            get {
                return ResourceManager.GetString("SelectDeviceIntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device.
        /// </summary>
        internal static string SelectDeviceText {
            get {
                return ResourceManager.GetString("SelectDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workout.
        /// </summary>
        internal static string SelectWorkoutText {
            get {
                return ResourceManager.GetString("SelectWorkoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Fitness Settings.
        /// </summary>
        internal static string SettingsPageNameText {
            get {
                return ResourceManager.GetString("SettingsPageNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup zones individually.
        /// </summary>
        internal static string SetupGarminOrSTZonesText {
            get {
                return ResourceManager.GetString("SetupGarminOrSTZonesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my speed between {0:0.00} {2}/h and {1:0.00} {2}/h..
        /// </summary>
        internal static string SpeedRangeTargetDescriptionText {
            get {
                return ResourceManager.GetString("SpeedRangeTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Settings.
        /// </summary>
        internal static string SpeedSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("SpeedSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my speed in a certain zone.
        /// </summary>
        internal static string SpeedTargetComboBoxText {
            get {
                return ResourceManager.GetString("SpeedTargetComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed Zones.
        /// </summary>
        internal static string SpeedZonesGroupBoxText {
            get {
                return ResourceManager.GetString("SpeedZonesGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to keep my speed in zone {0}.
        /// </summary>
        internal static string SpeedZoneTargetDescriptionText {
            get {
                return ResourceManager.GetString("SpeedZoneTargetDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportTracks.
        /// </summary>
        internal static string SportTracksText {
            get {
                return ResourceManager.GetString("SportTracksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string StepDetailsText {
            get {
                return ResourceManager.GetString("StepDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Duration.
        /// </summary>
        internal static string StepDurationGroupText {
            get {
                return ResourceManager.GetString("StepDurationGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When will this step end?.
        /// </summary>
        internal static string StepDurationLabelText {
            get {
                return ResourceManager.GetString("StepDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom step name:.
        /// </summary>
        internal static string StepNameLabelText {
            get {
                return ResourceManager.GetString("StepNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Target.
        /// </summary>
        internal static string StepTargetGroupText {
            get {
                return ResourceManager.GetString("StepTargetGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your target for this step?.
        /// </summary>
        internal static string StepTargetLabelText {
            get {
                return ResourceManager.GetString("StepTargetLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to use the SportTracks mode.
        /// </summary>
        internal static string STModeRadioButtonText {
            get {
                return ResourceManager.GetString("STModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using SportTracks zones, the plugin uses the heart rate and speed zones as defined in the category in which the workout is classified.  The SportTracks activity categories don&apos;t have cadence or power zones, this is why these must be defined independently..
        /// </summary>
        internal static string STZonesExplanationText {
            get {
                return ResourceManager.GetString("STZonesExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After I go a certain amount of time.
        /// </summary>
        internal static string TimeDurationComboBoxText {
            get {
                return ResourceManager.GetString("TimeDurationComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go for {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string TimeDurationDescriptionText {
            get {
                return ResourceManager.GetString("TimeDurationDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much time?.
        /// </summary>
        internal static string TimeDurationLabelText {
            get {
                return ResourceManager.GetString("TimeDurationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a duration between {0:00}:{1:00} and {2:00}:{3:00}.
        /// </summary>
        internal static string TimeRangeValidationText {
            get {
                return ResourceManager.GetString("TimeRangeValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Device.
        /// </summary>
        internal static string ToDeviceText {
            get {
                return ResourceManager.GetString("ToDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To File.
        /// </summary>
        internal static string ToFileText {
            get {
                return ResourceManager.GetString("ToFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string ToLabelText {
            get {
                return ResourceManager.GetString("ToLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is too recent for the version of the plugin installed.  Please install the latest version of the plugin..
        /// </summary>
        internal static string TooRecentDataText {
            get {
                return ResourceManager.GetString("TooRecentDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring to device.
        /// </summary>
        internal static string TransferringToDeviceText {
            get {
                return ResourceManager.GetString("TransferringToDeviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom category.
        /// </summary>
        internal static string UseCustomCategoryText {
            get {
                return ResourceManager.GetString("UseCustomCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use parent category.
        /// </summary>
        internal static string UseParentCategoryText {
            get {
                return ResourceManager.GetString("UseParentCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string ValueValidationTitleText {
            get {
                return ResourceManager.GetString("ValueValidationTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight :.
        /// </summary>
        internal static string WeightLabelText {
            get {
                return ResourceManager.GetString("WeightLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Garmin Fitness Plugin setup wizard.  This will help you setup the plugin for your logbook.  At any time, you can click on the &quot;Finish&quot; button to quit the wizard.  Also note that this wizard is always available from the plugin&apos;s &quot;Settings&quot; page so if you wish to configure the plugin later on, feel free to do so..
        /// </summary>
        internal static string WelcomeLabelText {
            get {
                return ResourceManager.GetString("WelcomeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel size.
        /// </summary>
        internal static string WheelSizeGroupBoxText {
            get {
                return ResourceManager.GetString("WheelSizeGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheel size :.
        /// </summary>
        internal static string WheelSizeLabelText {
            get {
                return ResourceManager.GetString("WheelSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which zone?.
        /// </summary>
        internal static string WhichZoneText {
            get {
                return ResourceManager.GetString("WhichZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SportTracks zones.
        /// </summary>
        internal static string WizardSTZonesText {
            get {
                return ResourceManager.GetString("WizardSTZonesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout link: {0}.
        /// </summary>
        internal static string WorkoutLinkStepText {
            get {
                return ResourceManager.GetString("WorkoutLinkStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string WorkoutsText {
            get {
                return ResourceManager.GetString("WorkoutsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of your workouts have more than 20 steps.  Those need to be split to reflect the changes in your options. Do you want to do this now?  You will need to do it manually if you choose &quot;No&quot;..
        /// </summary>
        internal static string WorkoutsWereSplitText {
            get {
                return ResourceManager.GetString("WorkoutsWereSplitText", resourceCulture);
            }
        }
    }
}
